1	SELECT DISTINCT plataforma FROM juegos;
2	SELECT * FROM juegos WHERE precioalquiler>4 && precioalquiler<6;
3	SELECT * FROM juegos order by plataforma ASC, nombre DESC;
4	SELECT nombre, precioVenta FROM juegos WHERE precioVenta<40;
5	SELECT * FROM juegos WHERE plataforma='PC';
6	SELECT DISTINCT plataforma, precioAlquiler FROM juegos;
7	SELECT nombre FROM juegos WHERE precioVenta IS NOT NULL ORDER BY precioVenta  ASC LIMIT 1;
8	SELECT id,nombre,precioVenta FROM juegos WHERE precioVenta>30 || precioVenta<20 ORDER BY precioVenta ASC;
9	SELECT plataforma FROM juegos WHERE precioAlquiler=4 LIMIT 1;
10	SELECT * FROM juegos WHERE stockAlquiler IS NULL;
11	SELECT * FROM juegos WHERE (plataforma='XBOX' OR plataforma='PC' OR plataforma='Playstation') AND precioVenta  BETWEEN 20 AND 50 ORDER BY nombre desc;
12	SELECT * FROM juegos WHERE precioAlquiler=3 OR precioAlquiler=5 OR precioAlquiler=8;
13	SELECT * FROM juegos ORDER BY nombre ASC LIMIT 4,3;
14	SELECT xogos.nombre, xogos.plataforma FROM juegos AS xogos LIMIT 3;
15	SELECT * FROM juegos WHERE nombre NOT LIKE '%&%';
16	SELECT DISTINCT plataforma FROM juegos WHERE plataforma LIKE '%p%';
17	SELECT nombre FROM juegos WHERE nombre LIKE 'M%';
18	SELECT nombre,plataforma FROM juegos WHERE stockAlquiler+stockVenta>10 AND nombre LIKE 'L%';
19	SELECT nombre FROM juegos where nombre LIKE 'M_N%' OR nombre LIKE 'L_N%';
20	SELECT * FROM juegos WHERE (stockVenta>=1 AND stockVenta<=10) AND (nombre LIKE '%O%') AND (precioVenta<30 OR precioVenta> 40);
21	SELECT * FROM juegos WHERE nombre LIKE '_a%' OR nombre LIKE '_e%' OR nombre LIKE '_i%' OR nombre LIKE '_o%' OR nombre LIKE '_u%';
22	SELECT * FROM juegos WHERE nombre NOT LIKE '_a%' AND nombre NOT LIKE '_e%' AND nombre NOT LIKE '_i%' AND nombre NOT LIKE '_o%' AND nombre NOT LIKE '_u%';