1	SELECT oficio, COUNT(oficio) AS 'num' FROM empleados GROUP BY oficio ORDER BY num DESC;
3	SELECT alumno, AVG(nota) AS 'media' FROM notas GROUP BY alumno;
4	SELECT oficio FROM empleados GROUP BY oficio HAVING COUNT(*)>2;
6	SELECT alumno, AVG(nota) AS 'media' FROM notas GROUP BY alumno HAVING media>5.7 ORDER BY media;
9	SELECT oficio,AVG(salario) AS media FROM empleados GROUP BY oficio HAVING media>2000;
11	SELECT iddepart, COUNT(oficio) AS numero FROM empleados WHERE oficio='empleado' GROUP BY iddepart;
13	SELECT iddepart, oficio, COUNT(codemp) AS numero FROM empleados GROUP BY oficio, iddepart HAVING numero>2;
16	SELECT codemp,apellido,salario from empleados WHERE salario>(select salario FROM empleados where codemp=6);
17	SELECT apellido,oficio from empleados WHERE oficio=(select oficio FROM empleados where apellido='Jimenez') AND apellido!='Jimenez';
18	SELECT apellido,salario from empleados WHERE oficio=(select oficio FROM empleados where apellido='Gil') AND salario=(select salario FROM empleados where apellido='Gil') AND apellido!='Gil';
21	SELECT * FROM empleados WHERE salario>(SELECT AVG(salario) FROM empleados);
23	SELECT iddepart,AVG(salario) AS media FROM empleados GROUP BY iddepart HAVING media>=(SELECT AVG(salario) FROM	empleados); 
26	SELECT COUNT(apellido) FROM empleados WHERE oficio='director'AND iddepart=(SELECT iddepart FROM depart WHERE nombre='ventas');
29	SELECT iddepart,nombre FROM depart WHERE iddepart NOT IN (SELECT iddepart FROM empleados);
32	SELECT nombre FROM asignaturas WHERE cod IN (SELECT asignatura FROM notas WHERE nota>4);
36	SELECT nombre, apellidos FROM alumnos WHERE codigo IN (SELECT alumno FROM notas WHERE nota=(SELECT nota FROM notas WHERE alumno=(SELECT codigo FROM alumnos WHERE nombre='frederik' AND apellidos='pohl') AND asignatura=(SELECT cod FROM asignaturas WHERE nombre='fol')));
38	SELECT * FROM empleados WHERE salario<ALL(SELECT salario FROM empleados WHERE iddepart=(SELECT iddepart FROM depart WHERE nombre='investigacion'));
39	SELECT * FROM empleados WHERE salario!=ANY(SELECT salario FROM empleados);
41	SELECT * FROM empleados AS emple WHERE NOT EXISTS (SELECT * From empleados where jefe=emple.codemp);
43	SELECT * FROM notas AS n WHERE exists(SELECT * FROM notas having MAX(nota)=n.nota);
46	SELECT * FROM empleados AS emple WHERE NOT EXISTS(SELECT * FROM empleados WHERE oficio=emple.OFICIO AND codemp!=emple.codemp);
48	SELECT apellido,salario,iddepart FROM empleados AS emple WHERE salario=(SELECT MAX(salario) FROM empleados WHERE iddepart=emple.IDDEPART);
